#!/bin/sh
git clone git@github.com:mk0v3l/personal.git
git clone git@github.com:mk0v3l/tp-ldp.git
git clone git@github.com:ulb-infof106/infof106-partie2-mk0v3l.git
git clone git@github.com:mk0v3l/tp-algo.git
git clone git@github.com:ulb-infof106/infof160-partie3-mk0v3l.git
git clone git@github.com:mk0v3l/script.git
git clone git@github.com:mk0v3l/projet-ldp.git

#git clone
#git clone
